---
abstract: 'Resolve Brazilian city data for a given CEP'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-CEP
requires:
  File::ShareDir: 0
  Moose: 0
  Text::CSV: 0
  common::sense: 0
version: 0.1
